#include <iostream>

const static std::vector<std::string> uwuQuotes = {
        "OwO, notice me, Senpai~",
        "Kyaaa~ Senpai, you're so kawaii!",
        "Senpai, let's watch anime together and cuddle~",
        "Nyaa~ Senpai, you're making my heart go doki-doki~",
        "Ehehe~ Senpai, you're my waifu/husbando!",
        "N-nani?! Senpai, you're embarrassing me~",
        "Senpai, let's do a kabe-don moment~",
        "S-senpai, please pat my head~",
        "UwU~ Senpai, you're my otaku prince/princess~",
        "Senpai, let's go to a maid café together~",
        "Ara ara~ Senpai, you're such a bishounen~",
        "Senpai, let's cosplay together at the next convention~",
        "Senpai, you're my sugoi hero~",
        "Senpai, my kokoro goes doki-doki whenever I see you~",
        "Senpai, you're my 2D crush come to life~",
        "Senpai, let's go on a date to Akihabara~",
        "Senpai, will you be the protagonist to my harem anime?",
        "Senpai, you're the onii-chan/onee-chan of my dreams~",
        "Senpai, let's reenact scenes from our favorite manga~",
        "Senpai, I'll be your loyal neko/catgirl maid~",
        "Senpai, let's binge-watch anime until the sun rises!",
        "OwO, Senpai, you're my ultimate senpai goal!",
        "Senpai, let's exchange bento boxes and have a picnic together!",
        "Ehehe~ Senpai, you're my ultimate ship!",
        "Senpai, let's confess our love under the cherry blossom trees!",
        "Nyaa~ Senpai, your smile is brighter than the sun!",
        "Senpai, let's embark on a journey to find the perfect ramen!",
        "OwO, Senpai, your otaku knowledge is truly impressive!",
        "Senpai, let's dance to the rhythm of our favorite anime openings!",
        "Senpai, you're the protagonist of my heart's story!",
        "Senpai, let's exchange manga recommendations and dive into new worlds together!",
        "Nyaa~ Senpai, you're my ultimate kawaii inspiration!",
        "Senpai, let's create our own anime together and become legends!",
        "Ehehe~ Senpai, you're my ultimate waifu/husbando material!",
        "Senpai, let's write our own love story filled with adventure and romance!",
        "Senpai, your presence alone lights up my world like a thousand stars!",
        "Senpai, let's visit the Studio Ghibli Museum and live out our own fairy tale!",
        "Nyaa~ Senpai, you're the protagonist of my dreams!",
        "Senpai, let's exchange dakimakuras and cuddle every night!",
        "Senpai, let's attend a cosplay contest and steal the show together!",
        "OwO, Senpai, you're my ultimate senpai goal!",
        "Senpai, let's exchange bento boxes and have a picnic together!",
        "Ehehe~ Senpai, you're my ultimate ship!",
        "Senpai, let's confess our love under the cherry blossom trees!",
        "Nyaa~ Senpai, your smile is brighter than the sun!",
        "Senpai, let's embark on a journey to find the perfect ramen!",
        "OwO, Senpai, your otaku knowledge is truly impressive!",
        "Senpai, let's dance to the rhythm of our favorite anime openings!",
        "Senpai, you're the protagonist of my heart's story!",
        "Senpai, let's exchange manga recommendations and dive into new worlds together!",
        "Nyaa~ Senpai, you're my ultimate kawaii inspiration!",
        "Senpai, let's create our own anime together and become legends!",
        "Ehehe~ Senpai, you're my ultimate waifu/husbando material!",
        "Senpai, let's write our own love story filled with adventure and romance!",
        "Senpai, your presence alone lights up my world like a thousand stars!",
        "Senpai, let's visit the Studio Ghibli Museum and live out our own fairy tale!",
        "Nyaa~ Senpai, you're the protagonist of my dreams!",
        "Senpai, let's exchange dakimakuras and cuddle every night!",
        "Senpai, let's attend a cosplay contest and steal the show together!",
        "OwO, Senpai, you're my ultimate senpai goal!",
        "Senpai, let's exchange bento boxes and have a picnic together!",
        "Ehehe~ Senpai, you're my ultimate ship!",
        "Senpai, let's confess our love under the cherry blossom trees!",
        "Nyaa~ Senpai, your smile is brighter than the sun!",
        "Senpai, let's embark on a journey to find the perfect ramen!",
        "OwO, Senpai, your otaku knowledge is truly impressive!",
        "Senpai, let's dance to the rhythm of our favorite anime openings!",
        "Senpai, you're the protagonist of my heart's story!",
        "Senpai, let's exchange manga recommendations and dive into new worlds together!",
        "Nyaa~ Senpai, you're my ultimate kawaii inspiration!",
        "Senpai, let's create our own anime together and become legends!",
        "Ehehe~ Senpai, you're my ultimate waifu/husbando material!",
        "Senpai, let's write our own love story filled with adventure and romance!",
        "Senpai, your presence alone lights up my world like a thousand stars!",
        "Senpai, let's visit the Studio Ghibli Museum and live out our own fairy tale!",
        "Nyaa~ Senpai, you're the protagonist of my dreams!",
        "Senpai, let's exchange dakimakuras and cuddle every night!",
        "Senpai, let's attend a cosplay contest and steal the show together!",
        "OwO, Senpai, you're my ultimate senpai goal!",
        "Senpai, let's exchange bento boxes and have a picnic together!",
        "Ehehe~ Senpai, you're my ultimate ship!",
        "Senpai, let's confess our love under the cherry blossom trees!",
        "Nyaa~ Senpai, your smile is brighter than the sun!",
        "Senpai, let's embark on a journey to find the perfect ramen!",
        "OwO, Senpai, your otaku knowledge is truly impressive!",
        "Senpai, let's dance to the rhythm of our favorite anime openings!",
        "Senpai, you're the protagonist of my heart's story!",
        "Senpai, let's exchange manga recommendations and dive into new worlds together!",
        "Nyaa~ Senpai, you're my ultimate kawaii inspiration!",
        "Senpai, let's create our own anime together and become legends!",
        "Ehehe~ Senpai, you're my ultimate waifu/husbando material!",
        "Senpai, let's write our own love story filled with adventure and romance!",
        "Senpai, your presence alone lights up my world like a thousand stars!",
        "Senpai, let's visit the Studio Ghibli Museum and live out our own fairy tale!",
        "Nyaa~ Senpai, you're the protagonist of my dreams!",
        "Senpai, let's exchange dakimakuras and cuddle every night!",
        "Senpai, let's attend a cosplay contest and steal the show together!",
        "OwO, Senpai, you're my ultimate senpai goal!",
        "Senpai, let's exchange bento boxes and have a picnic together!",
        "Ehehe~ Senpai, you're my ultimate ship!",
        "Senpai, let's confess our love under the cherry blossom trees!",
        "Nyaa~ Senpai, your smile is brighter than the sun!",
        "Senpai, let's embark on a journey to find the perfect ramen!",
        "OwO, Senpai, your otaku knowledge is truly impressive!",
        "Senpai, let's dance to the rhythm of our favorite anime openings!",
        "Senpai, you're the protagonist of my heart's story!",
        "Senpai, let's exchange manga recommendations and dive into new worlds together!",
        "Nyaa~ Senpai, you're my ultimate kawaii inspiration!",
        "Senpai, let's create our own anime together and become legends!",
        "Ehehe~ Senpai, you're my ultimate waifu/husbando material!",
        "Senpai, let's write our own love story filled with adventure and romance!",
        "Senpai, your presence alone lights up my world like a thousand stars!",
        "Senpai, let's visit the Studio Ghibli Museum and live out our own fairy tale!",
        "Nyaa~ Senpai, you're the protagonist of my dreams!",
        "Senpai, let's exchange dakimakuras and cuddle every night!",
        "Senpai, let's attend a cosplay contest and steal the show together!",
        "OwO, notice me, Senpai~",
        "Kyaaa~ Senpai, you're so kawaii!",
        "Senpai, let's watch anime together and cuddle~",
        "Nyaa~ Senpai, you're making my heart go doki-doki~",
        "Ehehe~ Senpai, you're my waifu/husbando!",
        "N-nani?! Senpai, you're embarrassing me~",
        "Senpai, let's do a kabe-don moment~",
        "S-senpai, please pat my head~",
        "UwU~ Senpai, you're my otaku prince/princess~",
        "Senpai, let's go to a maid café together~",
        "Ara ara~ Senpai, you're such a bishounen~",
        "Senpai, let's cosplay together at the next convention~",
        "Senpai, you're my sugoi hero~",
        "Senpai, my kokoro goes doki-doki whenever I see you~",
        "Senpai, you're my 2D crush come to life~",
        "Senpai, let's go on a date to Akihabara~",
        "Senpai, will you be the protagonist to my harem anime?",
        "Senpai, you're the onii-chan/onee-chan of my dreams~",
        "Senpai, let's reenact scenes from our favorite manga~",
        "Senpai, I'll be your loyal neko/catgirl maid~"
};

std::string getUwUQuote () {
    return uwuQuotes.at(rand() % uwuQuotes.size());
}